route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: '1106q'
            channel: '#test'
            api_url: 'https://hooks.slack.com/services/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'