cluster.name: "docker-cluster"

network.host: 0.0.0.0

discovery.seed_hosts: 0.0.0.0:9200
discovery.type: single-node

# cluster.inital_master_nodes: ["node-1"]

http.cors.enabled: true 
http.cors.allow-origin: "*"

xpack.license.self_generated.type: trial
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
