cluster.name: "docker-cluster"

network.host: 0.0.0.0

discovery.seed_hosts: ["elasticsearch"]
discovery.type: single-node

# cluster.inital_master_nodes: ["node-1"]

xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
