# Generated by Django 4.1.5 on 2023-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey_apple_app', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
