name: Dockerizing to Amazon ECR

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - feature#110

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: heyapple


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Clone github repository hey_apple
      run: git clone https://github.com/2022-Winter-Bootcamp-team-L/hey_apple.git

    - name: Create secrets.json file
      working-directory: ./backend
      run: |
          pwd
          touch secrets.json
          echo "${{secrets.SECRETS_JSON}}" >> secrets.json
          cat secrets.json

    - name: Build docker images
      run: |
          docker-compose build
          docker images

    - name: Push images to Amazon ECR repositorys
      run: docker-compose push



    # - name: Build, tag, and push image to Amazon ECR
    #   id: build-image
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     IMAGE_TAG: ${{ github.sha }}
    #   run: |
    #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #     echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
